### ISSUE TITLE
Please enable older cmake versions

### ISSUE THREAD

**Issue by lemzwerg** [adobe/svg-native-viewer#10]
The necessary cmake version 3.7.2 to build the library is only two years old.  Many GNU/Linux distributions, however, come with older versions by default; for example, my up-to-date openSuSE Leap 42.3 box contains version 3.5.2.

I'm not a cmake expert so I don't know whether it is easy to allow older versions easily.  It would be great to make it possible to build everything with, say, cmake versions three or four years old.

**Comment by mpsuzuki** [comment]
I tested Ubuntu16.04 LTS whose cmake is 3.5.1. After tweaking the required version from 3.7.2 to 3.5.0 and the installation g++-7 from ppa:ubuntu-toolchain-r/test, the building process itself finishes successfully. I guess you've already done similar experiment. If you find some troubles to be fixed, please let me know. I want to check before submitting pull request. (ah, I've not checked whether older cmake works well on other platforms like macOS or Windows)

https://github.com/mpsuzuki/svg-native-viewer/commit/92729bfc576413af87769e288307c783c26f69be

**Comment by dirkschulze** [comment]
Downgraded to 3.5.0. Maybe even earlier versions work too. IIRC the used features got back to 3.0 or 3.1. Would need more testing on older CMAKE versions.
