### ISSUE TITLE
StringSVGRenderer writes quad beziers as "T" instead of "Q"

### ISSUE THREAD

**Issue by anthrotype** [adobe/svg-native-viewer#100]
Why does the `StringSVGRenderer::CurveToV` method writes quadratic bezier curves with the "T" command? Should it not use "Q"?

https://github.com/adobe/svg-native-viewer/blob/ef627051444b7c2041860bd4d0fe5232e2ba8aa2/svgnative/ports/string/StringSVGRenderer.cpp#L49

I got a bit confused the first time I saw this.
"T" is the shorthand path command for smooth quadratic bezier curves; it only has one argument as the quad curve control point is implicit (reflection of the control point from the previous command).
"Q" command seems to describe better what "CurveToV" method is doing, as it's the explicit form for the quadratic bezier curve, with two arguments.

I got also confused by the method name "CurveToV". I was expecting more like "QuadTo".

Anyway, no big deal. I just wanted to point this out. Feel free to close this, thanks.

**Comment by mpsuzuki** [comment]
Thank you for finding this. I think the correction is needed. At present, StringSVGRenderer's output is not designed for re-renderable as a graphics, that's why you commented "no big deal"?
