### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [adobe/svg-native-viewer#108]
Memory is allocated
https://github.com/adobe/svg-native-viewer/blob/b506978734f650a52cbc9f689abc10655cb9bcb6/svgnative/ports/cairo/CairoSVGRenderer.cpp#L169
but at the end of function，never free it
https://github.com/adobe/svg-native-viewer/blob/b506978734f650a52cbc9f689abc10655cb9bcb6/svgnative/ports/cairo/CairoSVGRenderer.cpp#L180

**Comment by mpsuzuki** [comment]
Thank you for taking a look on this!!

If I'm understanding the [cairo document](https://www.cairographics.org/manual-1.10.2/cairo-cairo-surface-t.html#cairo-surface-set-mime-data) correctly, the data passed to a cairo surface via cairo_surface_set_mime_data() function, blob_data is that in our case, it would not be duplicated immediately, on the other hand, it would be used in later, by device-dependent mechanisms. So we should not free the data passed via cairo_surface_set_mime_data() function after returning from this function.

To free the memory used by the data passed by this function, when the surface is destroyed or when some new data with same mime type (and previous one would not be used anymore), the surface would call a function to destroy the data, with a preset argument (closure). In our case, I set free() as the destroyer, and blob_data as the closure to be passed to the destroyer.

If you find any example of the expected leak, or, if you have a proposal for improvement, please let me know.

Thanks in advance!

**Comment by dirkschulze** [comment]
Closing this. As @mpsuzuki pointed out, we pass the `free` function so that cairo can destroy the image. We do correctly free when there has been any error.

With no response from the reported, I am going to close this issue.
