### ISSUE TITLE
'usvg' tool by Evgeniy Reizner

### ISSUE THREAD

**Issue by twardoch** [adobe/svg-native-viewer#109]
Evgeniy Reizner (@RazrFalcon ) is developing his [ReSVG](https://github.com/RazrFalcon/resvg/) rasterizer, an MPL-licensed library written in Rust.

I've [notified him](https://github.com/RazrFalcon/resvg/issues/135) about SVG Native last year, and now once again as the [spec](https://svgwg.org/specs/svg-native/) gets solidified. It seems that he's willing to support SVG Native, and perhaps might derive a more compact “ReSVG Native” version of the library. 

It looks like currently, ReSVG uses its own image buffers and compositing rather than drawing to backends with contour methods (so it is, above all, a rasterizer). This may, of course, change. 

One interesting aspect of the ReSVG project is his ['usvg' tool](https://github.com/RazrFalcon/resvg/blob/master/README.md) that creates a simplified SVG. 

Currently, usvg uses his own [Micro SVG](https://github.com/RazrFalcon/resvg/blob/master/docs/usvg_spec.adoc) subset of SVG which has significant overlap with SVG Native. 

As SVG Native progresses, I think it’ll be wonderful to have two independent rasterizing implementations exist (the Adobe SVG Native Viewer and ReSVG), and of course a tool that is able to convert SVG to SVG Native. 

If this project can lend any assistance to ReSVG, I think this would be highly beneficial for anyone interested in SVG Native.

Thanks!
Adam

**Comment by dirkschulze** [comment]
Hi @twardoch. Thanks for your comment. This is the bug tracker for svg-native-viewer. I am going to close this issue as there is no issue reported with svg-native-viewer.

**Comment by twardoch** [comment]
Yeah — I just wanted to make that connection. No reason to keep the issue open.
