### ISSUE TITLE
Compilation failure on openSUSE Leap 42.3 with g++ 7.4.0 and 8.3.1

### ISSUE THREAD

**Issue by lemzwerg** [adobe/svg-native-viewer#12]
[3e168dab8eaa41d7174b9329deefa0620d677a35, with the fix mentioned in issue #11]

Calling
```
cmake -D CMAKE_C_COMPILER=gcc-7 -D CMAKE_CXX_COMPILER=g++-7 -BBuild/linux -H.
```
followed by calling `make` fails with
```
[ 25%] Building CXX object CMakeFiles/SVGNativeViewerLib.dir/src/SVGDocumentImpl.cpp.o
In file included from .../svg-native-viewer/svgnative/src/SVGDocumentImpl.h:15:0,
                 from .../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:13:
.../svg-native-viewer/svgnative/include/SVGRenderer.h:129:10:
  error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
     std::shared_ptr<Transform> transform; /** Joined transformation matrix based to the "transform" attribute. **/
          ^~~~~~~~~~
```
I guess it's probably the same as issue #11, this is, `CMakeLists.txt` lacks a test whether the specified g++ version supports the necessary C++14 features.

**Comment by lemzwerg** [comment]
I get the same error with g++ 8.3.1.

**Comment by dirkschulze** [comment]
This should be fixed with the `<memory>` include.

**Comment by dirkschulze** [comment]
FYI, the CircleCI build uses g++ 6 (Debian). Locally I am running g++ 7.3.0 (Ubuntu). Both did not complain. Maybe some clean-up that happened in later versions?

**Comment by lemzwerg** [comment]
No idea, sorry.
