### ISSUE TITLE
Glyph id within the root SVG element

### ISSUE THREAD

**Issue by dejanyy** [adobe/svg-native-viewer#123]
In the attached SVG file, the glyph id is associated with the root SVG element:

<svg id="glyph53" ...
<path ... >

Full file: [strange_looking_k.svg.txt](https://github.com/adobe/svg-native-viewer/files/5491341/strange_looking_k.svg.txt)

I believe this is contrary to the OpenType SVG spec (judging by the "Glyph Identifiers" section at https://docs.microsoft.com/en-us/typography/opentype/spec/svg), but who knows...

It looks like SVG Native can't find glyph ids that are attached to the root svg element.

However, the above SVG file is extracted from a font called BungeeColor-Regular_svg.ttf, so it appears there are fonts out there that like to attach glyph ids to the root svg element.

BTW, I have also encountered SVG fonts that put "transform", "color" and similar attributes inside the root SVG element. I don't know if any SVG specification allows this, but crappy fonts like that do exist. SVG Native seems to ignore all those attributes.

**Comment by dirkschulze** [comment]
Hi @dejanyy . #122 is addressing the id issue as well as all CSS properties that get ignored. SVG root element does not support the `transform` attribute so sag-native-viewer ignores it.

**Comment by dirkschulze** [comment]
Fixed by #122
