### ISSUE TITLE
Null pointer dereference/Default delete bug

### ISSUE THREAD

**Issue by docfate111** [adobe/svg-native-viewer#127]
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000004455df in std::__uniq_ptr_impl<SVGNative::SVGDocumentImpl, std::default_delete<SVGNative::SVGDocumentImpl> >::_M_ptr() const ()
```
In the method  svg_native_render() in build/linux/example/testC/testC on Ubuntu 20.04
with input 
```
<!-- |%|
```
saved as a file and passed as argument to testC

**Comment by dirkschulze** [comment]
Can confirm the issue. There is a missing null check for `mDocument` in https://github.com/adobe/svg-native-viewer/blob/master/svgnative/src/SVGNativeCWrapper.cpp#L222 for this crash but in other places as well:

```
svg_native_canvas_width
svg_native_canvas_height
svg_native_render
svg_native_render_size
```

**Comment by dirkschulze** [comment]
While I checked for `mDocument`, same issue with `mRenderer`.

**Comment by docfate111** [comment]
```
svg-native-viewer/svgnative/src/SVGNativeCWrapper.cpp
   221     auto _sn = dynamic_cast<svg_native_t_*>(sn);
   222     if (!_sn)
   223         return;
   224     
   225     if (_sn->mColorMap)
 ► 226         _sn->mDocument->Render(_sn->mColorMap->mColorMap);

```
The bug is in svg-native-viewer/svgnative/src/SVGNativeCWrapper.cpp line 226 when Render is called

**Comment by dirkschulze** [comment]
Thanks a lot for @docfate111 reporting this issue!

**Comment by docfate111** [comment]
Thanks for working towards fixing
