### ISSUE TITLE
Getting elements from empty vector

### ISSUE THREAD

**Issue by docfate111** [adobe/svg-native-viewer#128]
Ubuntu 20.04 using the binary svg-native-viewer/svgnative/build/linux/example/testText/testSVGNative.
The numberList vector is empty but is indexed which causes a segmentation fault.
```
svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp
   343         {
   344             std::vector<float> numberList;
   345             if (SVGStringParser::ParseListOfNumbers(attr.value, numberList) && numberList.size() == 4)
   346                 graphicStyle.transform = mRenderer->CreateTransform(1, 0, 0, 1, -numberList[0], -numberList[1]);
   347             {
 ► 348                 mViewBox = {{numberList[0], numberList[1], numberList[2], numberList[3]}};
   349             }
   350         }
```
Github isn't letting me upload the file

**Comment by dirkschulze** [comment]
This seems like an oversight: Both commands are supposed to be within the same block and only get executed when the vector has 4 elements.

Thanks for the finding @docfate111 !

**Comment by dirkschulze** [comment]
It is part of the `<symbol>` `viewBox` attribute. Line 348 shouldn't be there at all.

I can reproduce the issue with:
```xml
<svg width="20" height="20">
<symbol viewBox="10 20 30" id="invalid-viewBox">
    <rect width="20" height="20" />
</symbol>
<use xlink:href="#invalid-viewBox" />
</svg>
```

**Comment by dirkschulze** [comment]
Issue fixed and regression test added.

Thanks again @docfate111 for testing and opening this issue!

**Comment by docfate111** [comment]
Thanks for fixing
