### ISSUE TITLE
Compilation failure with g++ 4.8.5 on 'cpp11' branch

### ISSUE THREAD

**Issue by lemzwerg** [adobe/svg-native-viewer#14]
[a319af7623671250aada5d920292016c8f5a0bc5]

Compiling the `cpp11` branch with g++ 4.8.5 yield an error; the log file starts as follows.
```
[ 12%] Building CXX object CMakeFiles/SVGNativeViewerLib.dir/src/SVGDocumentImpl.cpp.o
.../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:
  In member function ‘std::unique_ptr<SVGNative::Path>
    SVGNative::SVGDocumentImpl::ParseShape(SVGNative::XMLNode*)’:
.../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:528:18:
  error: no match for ‘operator>’ (operand types are
    ‘std::initializer_list<long unsigned int>’ and ‘int’)
         if (size > 1)
                  ^   
.../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:528:18: note: candidates are:
In file included from /usr/include/c++/4.8/stack:61:0,
                 from .../svg-native-viewer/svgnative/src/SVGDocumentImpl.h:23,
                 from .../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:13:
/usr/include/c++/4.8/bits/stl_stack.h:273:5:
  note: template<class _Tp, class _Seq>
    bool std::operator>(const std::stack<_Tp, _Seq>&, const std::stack<_Tp, _Seq>&)
     operator>(const stack<_Tp, _Seq>& __x, const stack<_Tp, _Seq>& __y)
     ^
/usr/include/c++/4.8/bits/stl_stack.h:273:5: note:
   template argument deduction/substitution failed:
.../svg-native-viewer/svgnative/src/SVGDocumentImpl.cpp:528:20: note:
   ‘std::initializer_list<long unsigned int>’ is not derived from
    ‘const std::stack<_Tp, _Seq>’
         if (size > 1)
                    ^ 
...
```

**Comment by dirkschulze** [comment]
@lemzwerg Is  g++ 4.8.5 support needed? It looks like an issue with the initialization list in C++11 in the beginning. Try replacing `auto size{numberList.size()};` with `size_t size = numberList.size();`. My guess is that this fixes the issue.

**Comment by lemzwerg** [comment]
Support for g++ 4.8.5 is of course *not* needed (well, it would be nice, since this version is approx. five years old, which is not very ancient).  However, it should be either documented that a newer version is needed, or – even better – the cmake support files should be adjusted to either check whether the necessary functionality is available (in the good old autoconf style), or reject too old g++ versions.  Thus my reports :-)

Your suggested change indeed works!  It still fails with another error, though, see
[attached log file](https://github.com/adobe/svg-native-viewer/files/3101543/make.log).

**Comment by dirkschulze** [comment]
All of the issues seem to be related to C++ initialization list.

**Comment by lemzwerg** [comment]
If you say so :-)  By the way, the `cpp11` branch (plus your suggested change applied) fails with g++ 5.3.1 also.
