### ISSUE TITLE
Gradients don't seem to work

### ISSUE THREAD

**Issue by moazin** [adobe/svg-native-viewer#149]
It seems that both linear and radial gradients don't work, neither in Cairo nor Skia port. Haven't tested CG or GDI+ yet.

The document is:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" width="1000" height="1000">
  <defs>
    <linearGradient id="myGrad">
      <stop offset="5%" stop-color="red" />
      <stop offset="100%" stop-color="blue" />
    </linearGradient>
    <radialGradient id="myGradRadial">
      <stop offset="5%" stop-color="red" />
      <stop offset="100%" stop-color="blue" />
    </radialGradient>
  </defs>
  <rect x="100" y="100" width="200" height="200" fill="url(#myGrad)" />
  <circle cx="300" cy="500" r="100" fill="url(#myGradRadial)" />
</svg>
```
Rendering by Librsvg:
![image](https://user-images.githubusercontent.com/23481137/118971049-640a0080-b988-11eb-8fb0-69cffa0b1420.png)
Rendering by SNV (Cairo) and SNV (Skia):
![image](https://user-images.githubusercontent.com/23481137/118971097-6ff5c280-b988-11eb-97cf-bf1b5c70e206.png)

**Comment by moazin** [comment]
Please have a look at the documentation for a `linearGradient` [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/linearGradient). As you can see, there is an attribute there called `gradientUnits`. The value is either `userSpaceOnUse` or `objectBoundingBox`. By default, it's the latter one. These specify the coordinate system for the actual points of the gradient. The default coordinates in case of a linear gradient are (0, 0) to (1, 0). The problem is that SNV just assumes its `userSpaceOnUse` and just calls the underlying gradient functions of the port. 

As far as I can see, [cairo](https://www.cairographics.org/manual/cairo-cairo-pattern-t.html) can't automatically use the `objectBoundingBox` coordinate system, we'll have to find a transformation to that system and apply it by using the `cairo_pattern_set_matrix` function. I think the same holds for Skia too. I still need to check the rest of them.

**Comment by anthrotype** [comment]
it seems objectBoundingBox was deliberately dropped in svg-native, see the README https://github.com/adobe/svg-native-viewer#supported-features-in-svg-native-in-comparison-to-svg11svg2

> No support of objectBoundingBox on gradientUnits

**Comment by moazin** [comment]
@anthrotype Oh right. Thank you for pointing this out. I just went through the SVG Native standard and it doesn't support `objectBoundingBox`. See [this](https://svgwg.org/specs/svg-native/#pservers).

**Comment by moazin** [comment]
@sairuspatel It looks like we've run into the first discrepancy between the SVG Native standard and the reduced subset of SVG that OT-SVG uses. The SVG Native standard doesn't support `objectBoundingBox`, however, OT-SVG says nothing about it and the [example 2](https://docs.microsoft.com/en-us/typography/opentype/spec/svg) even uses it. 

@sairuspatel @litherum Any idea why the SVG Native standard prohibits `objectBoundingBox`?

**Comment by moazin** [comment]
I've iterated through all of the glyphs used in NotoColor and Trajan and it seems that neither of those use `objectBoundingBox` so we are good. However, I'd like to still keep this open until I explore more fonts that are out there and rely on gradients.

**Comment by tjindal** [comment]
@moazin  can you please advise why you have closed this issue ? As of now in SNV these gradient units are not working.
