### ISSUE TITLE
Provide a C Wrapper

### ISSUE THREAD

**Issue by dirkschulze** [adobe/svg-native-viewer#16]
Some clients require a C wrapper for SVG Native Viewer.

**Comment by mpsuzuki** [comment]
Now I'm working with a preliminary [wrapper](https://github.com/mpsuzuki/svg-native-viewer/tree/c-api/svgnative/example/c-api) for C clients.
At present, graphic context (or canvas) which C clients can manage by themselves is only Cairo. For the people who write C programs but want to use Skia or Qt backend, the wrapper should help the management of graphic contexts and provide more simple-minded functions, like, svg_to_png() ?

**Comment by dirkschulze** [comment]
@mpsuzuki @moazin I think the easiest solution for `std::map` would be to create a wrapper for `std::map` similar to https://stackoverflow.com/a/29861747

```cpp
void* get_svg_native_color_map();
void insert_to_svg_native_color_map(void* color_map, const char* key_string, float* rgb_color);
```

**Comment by lemzwerg** [comment]
Dirk, do you have an estimate when we have a C API wrapper in `master`?

**Comment by mpsuzuki** [comment]
I should add other ports (e.g. GDI+ and Cairo) into C API wrapper...

**Comment by mpsuzuki** [comment]
@lemzwerg I confirmed current C wrapper needs more work. You can find the current code tries to dynamic_cast from void pointer to a pointer to the renderer class, and causes [a compile error](https://circleci.com/gh/adobe/svg-native-viewer/328). I confirmed same error in SKIA port on GNU/Linux. Some tweaks for C API are needed...

**Comment by mpsuzuki** [comment]
I my [C-API branch](https://github.com/mpsuzuki/svg-native-viewer/tree/c-api/svgnative/example/c-api), I used a pointer to a structure [SVGNative_Hive](https://github.com/mpsuzuki/svg-native-viewer/blob/f01eecea515082b9783cf44876320d5de7298306/svgnative/example/c-api/SVGNativeCAPI.h#L15), which includes both of the [renderer and document](https://github.com/mpsuzuki/svg-native-viewer/blob/f01eecea515082b9783cf44876320d5de7298306/svgnative/example/c-api/SVGNativeCAPI.cpp#L33)

**Comment by dirkschulze** [comment]
@mpsuzuki I am open to another approach. What ever API is easier to use for clients that need the C wrapper.

@lemzwerg I don't know how much more time I need. If/When @mpsuzuki has a working wrapper for all rendering libs we can use that one.

**Comment by dirkschulze** [comment]
@moazin @lemzwerg We landed the C wrapper. It would be great if you could take a look and provide feedback.

IMO (with the exception of #84 that @mpsuzuki is working on) this is the last remaining peace for a stable ABI.
Unless you raise concerns with the interface we can move to a stable major version soon.

Here the header with the documentation: https://github.com/adobe/svg-native-viewer/blob/master/svgnative/include/SVGNativeCWrapper.h
Here the example app: https://github.com/adobe/svg-native-viewer/blob/master/svgnative/example/testC/TestMain.cpp

**Comment by lemzwerg** [comment]
Thanks a lot, it looks great!

Some comments.

* There is a typo in `SVGNativeCWrapper.h`: s/negetive/negative/
* What about having a header file `svgnative.h` instead of the long name?  Or maybe `SVGnative.h`.
* I think it would make sense to actually use a C compiler for testing the wrapper interface.  Sometimes, there are subtle differences of what's allowed and what not.

**Comment by mpsuzuki** [comment]
@lemzwerg Indeed, I would try to rewrite TestC.cpp into TestC.c.

**Comment by mpsuzuki** [comment]
@lemzwerg I drafted a PR #86 to replace testC/TestMain.cpp by testC/TestMain.c. I replaced a few types for the length of data, from int to size_t. If it's not good for the consistency, please let me know, I would replace them to int.

**Comment by lemzwerg** [comment]
Yes, `size_t` is the right thing.

**Comment by dirkschulze** [comment]
Closing as fixed now. Thank you everyone for the help and participation!
