### ISSUE TITLE
Support rendering by 'id'

### ISSUE THREAD

**Issue by dirkschulze** [adobe/svg-native-viewer#26]
SVG OT allows adding multiple glyphs to the same SVG document. On rendering, the client needs to be able to choose which glyph to render by specifying an element node id.

**Comment by mpsuzuki** [comment]
OpenType spec mentions a technique to enclose whole document into <defs> element and invoke specific object by <use> element after <defs> element. There are some elements which we cannot put into <defs>, but as far as I could check, all SVG Native elements could be inserted into <defs> element. 

So, it would be a considerable option to give a small modification function, which push everything into <defs> and append single <use> element. But it is bad idea to synthesize modified SVG document in each request?

**Comment by dirkschulze** [comment]
@mpsuzuki https://github.com/adobe/svg-native-viewer/tree/render-element-by-id already implemented the functionality. It just does not expose the functionality to the API level of `SVGDocument` yet.

The entire document gets parsed in the bounds of the SVG document's `viewBox`. IDs of shapes and groups get added to a common, internal map with the render-object representing those shapes.

One just needs to pass an ID-String and SVG Native Viewer would render the referenced element only (should it exist).

I am just not sure how to expose the option on the API level yet.
* I want to avoid adding too many arguments to the function calls.
* Make the APIs stable in the long term.

So I am thinking about an options `struct` as argument that we could extend over time. However, I'd like to avoid that clients need to do a lot of copy operations to generate the struct. Especially C APIs that do not use the stdlib constructs like `std::map` might run into bigger issues (creating copies on every rendering call) with such a concept. I am open to suggestions.

**Comment by mpsuzuki** [comment]
Great thank you for taking care on this, and sorry for my silence. Indeed, some struct is easier for most C implementations, rather than std::map or its replacements.
If we think about very FreeType-specific solution, FT has an internal object, FT_Hash, which is used to handle the key-value dictionaries in BDF and Type1 font parser. I would ask Werner's comment about the utilization of FT_Hash for SVG. Please wait a while...

**Comment by dirkschulze** [comment]
@mpsuzuki any update on this?

**Comment by mpsuzuki** [comment]
Sorry for my silence about this. I discussed with @lemzwerg, and the exposure of FT_Hash is regarded not to be best if the API is frequently used (e.g. if FT_Hash -> std::map is executed for each glyph rendering). I had to return to the original idea to have C-like API to pass the parameters.
Now @moazin is doing the experiments of SVG-OT with resvg, and would design the callback APIs. I would take a look on this current code and try to make a proposal.

**Comment by dirkschulze** [comment]
@mpsuzuki Seems like the `std::map<std::string, std::array<4, float>>` is the major issue for a C wrapper. Did you look at C alternatives for it?

**Comment by mpsuzuki** [comment]
I found that, in Moazin's glue code between FreeType2 and resvg [available from GoogleDrive](https://drive.google.com/open?id=1Nl0mtExvXXzuCdUvURAPzqGS0Ed-5K7J), the glue code creates a wrapper instance with a persistent variable to store the rendering option (but, most of the rendering options for resvg is the switches for simplification for quick rendering). The metric of the SVG graphic is returned from resvg library, but the specification of the area to be rendered is controlled out of resvg (by using Cairo context). Considering this current situation, the option from the client to SVG Native Viewer would be only string to specify the object to render, and the pointer to the structure for SVG Native Viewer to write the metric info. So, a structure like
```
typedef struct svg_native_viewer_option {
  uint32_t  version; /* to declare 
  double bbox[4];
  unsigned char*  id_to_render;
} svg_native_viewer_option;
```
 would be sufficient.

However, considering that the glue code may have a persistent variable, I think it is considerable option that SVG Native Viewer provides C++ interface taking std::map object, and the glue code provides some APIs to manipulate the std::map object. How do you think about a situation which we have SVG Native Viewer with C++ interface only, and another wrapper library for C?

**Comment by moazin** [comment]
The code is also available from this [repo](https://bitbucket.org/moazin/resvg-port-freetype-otsvg/src/master/). I have just implemented the `glyph_by_id` feature too. There are some minor issues which are probably `resvg` specific. but it is functional. Also note that the way this glue code is written can be changed without much effort. So if you guys see some problems and know of better ways please let me know! :)

**Comment by moazin** [comment]
@mpsuzuki @dirkschulze One thing that I'd like to mention here is the behavior of `resvg` and `librsvg` when it comes to rendering by ID. Both take into account viewbox translations when rendering the whole SVG document, however, if you are rendering by ID, `librsvg` still takes into account the viewbox translation but `resvg` doesn't. I could be wrong here but this is what my experiments with these libraries show so far. I don't know which behavior is the right one here and even for OT-SVG it doesn't matter much as long as SVG Native Viewer provides an API function to retrieve the complete viewbox, [see](https://github.com/adobe/svg-native-viewer/issues/33#issue-465270175). My personal preferences would be the behavior of `librsvg`, taking into account viewbox translations regardless of whether the whole doc is being rendered or just a particular element.

**Comment by dirkschulze** [comment]
@moazin Translating by the first 2 values in the `viewBox` attribute is correct. This probably is just missing in `resvg` but likely would be easy to fix there as well.
