### ISSUE TITLE
dashed line support in Skia backend

### ISSUE THREAD

**Issue by mpsuzuki** [adobe/svg-native-viewer#27]
Now I'm working on dashed line support in Skia backend ( https://github.com/mpsuzuki/svg-native-viewer/tree/add-dashed-line-to-skia ). Please let me ask a design question before making a pull request.

For Cairo backend, dashed line support was very easy ( 9f188d341e12adc10bda1d02fd709f5c5d851214 ), because Cairo's API is almost side-by-sidely designed for SVG. For example, dashed-array is expected to be even-sized array, but the fallback for odd-sized array is also defined. Even if I pass odd-sized dash array to Cairo, it works as SVG spec expects.

On the other hand, it seems that Skia has no such builtin fallback for odd-sized array ( [SkDashPathEffect::Make()](https://skia-doc.commondatastorage.googleapis.com/doxygen/doxygen/html/classSkDashPathEffect.html) ). For example, if I pass only 1 member dashed-array, the result is normal line. It is not difficult to implement the fallback behaviour in Skia backend (like this eb4e08afbb313864eba647e74c6950c1a85acf5a ).

But, such fallback is defined by SVG spec [stroke properties](https://www.w3.org/TR/SVG11/painting.html#StrokeProperties) , should I implement something in SVG document parser side, to reduce the cost of backend-specific fallback for future developers?

**Comment by dirkschulze** [comment]
@mpsuzuki I think it is fine to implement the stroke dash array correction on the parser side.

**Comment by mpsuzuki** [comment]
Thanks, just I've revised like d661bd64fb3f3579b55b665fb97d5d0105245d27 . By this changeset, some text files generated by string backend are different from those in test directory already, like test/dash-array.txt. They should be included in PR?

**Comment by mpsuzuki** [comment]
I made PR https://github.com/adobe/svg-native-viewer/pull/42 for this.
Thanks in advance.

**Comment by mpsuzuki** [comment]
Thank you for accepting PR #42 !
Here I close this issue :-)
