### ISSUE TITLE
Support for `linearGradient` and related outside `defs` doesn't exist

### ISSUE THREAD

**Issue by moazin** [adobe/svg-native-viewer#36]
In one of the test fonts we were given for OT-SVG that you can find [here](https://github.com/unicode-org/text-rendering-tests/blob/master/fonts/TestSVGmultiGlyphs.otf), I found an [SVG document](https://github.com/adobe/svg-native-viewer/files/3395980/out.svg.txt)
having a `radialGradient` element outside `defs` section. This is allowed in SVG specs, AFAIK. However, such an element is totally ignored by SVG Native Viewer.

**Comment by dirkschulze** [comment]
@moazin That is indeed a limitation in SVG Native Viewer and can be fixed easily. Thanks for reporting.
