### ISSUE TITLE
Support Cairo backend

### ISSUE THREAD

**Issue by dirkschulze** [adobe/svg-native-viewer#39]
Add SVGRenderer for a Cairo Graphics backend.

**Comment by dirkschulze** [comment]
@mpsuzuki You created a Cairo Graphics backend already as far as I remember. Would you be willing to contribute it to this repo?

**Comment by mpsuzuki** [comment]
I apologize my long long long absence from svg-native-viewer development, to you, @moazin and @lemzwerg. Yes, I'm willing to contribute. Please let me spend some time to update my code tree to sync with the latest.
My PC has been broken since this summer, I have to prepare my environment.

**Comment by mpsuzuki** [comment]
Just I've made a PR https://github.com/adobe/svg-native-viewer/pull/43 ,
please give me some comments for more improvements.

**Comment by mpsuzuki** [comment]
Great thank you for continous and patient effort to clean up my PR!
