### ISSUE TITLE
reusing a path element from <defs> through xlink:href doesn't work?

### ISSUE THREAD

**Issue by anthrotype** [adobe/svg-native-viewer#68]
I have something like this:

```xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="150" height="250" viewBox="0 0 150 250">
    <defs>
        <path id="foo" d="M 20 100 L 40 100 L 40 120 L 20 120 z"/>
    </defs>
    <use xlink:href="#foo"/>
    <use xlink:href="#foo" fill="green" transform="translate(50, 0)"/>
    <use xlink:href="#foo" fill="red" transform="translate(100, 0)"/>
</svg>
```

When I run this trough `example/testText/testSVGNative` the result is empty:

```
[group transform: matrix(1,0,0,1,0,0)
    [group
    ]
]
```

Is this possible in the SVG Native format to reference a path element defined inside `<defs>` with a `<use xlink:href=#id/>`? I thought it should be possible.

Thanks

**Comment by mpsuzuki** [comment]
@anthrotype Thank you for finding this issue, I've confirmed it.

I've checked the source code, and find that <defs>...</defs> and <use xlink:href="#xxx"> are really taken into account, around https://github.com/adobe/svg-native-viewer/blob/af8bdabe1f87476de34e8e8eed58df9b28d853ff/svgnative/src/SVGDocumentImpl.cpp#L317

But, tracing the behaviour for your sample, it seems that no real path construction or painting is exected, and text backend does not push any member (I think). Please let me spend more time what's going on, or, this is designed behaviour. Sorry for your inconvenience.
