### ISSUE TITLE
rx == 0 or ry == 0 ellipse or rectangle can paralyze Cairo port, at least.

### ISSUE THREAD

**Issue by mpsuzuki** [adobe/svg-native-viewer#69]
During the investigation of my patch for Issue #67, I found my cairo port is paralyzed by the ellipse or rectangles with rx == 0 or ry == 0. I think Skia and CoreGraphics ports are safe from this issue, because they have direct functions to draw ellipse or rounded-rectangle.

Cairo has no direct functions to draw ellipse or rounded-rectangle, so I inserted cairo_scale() to stretch the circle or rounded-corner of the rounded rectangle. Maybe, cairo_scale(cr, 0, scale_y) or cairo_scale(cr, scale_x, 0) and following cairo_arc() makes cairo confused, and all following objects are not drawn correctly.

So, I drafted a patch to replace ["rx == 0 or ry == 0 ellipse" by a squashed bounding-box](741849aba4f98fbd5d7c3fbceeaa46a21f9ff331), and to replace ["rx == 0 or ry == 0 rounded rectangle" by normal rectangle](0df194c5a36d5e694996858db87feaab12bac286).

Another option might be "if an ellipse or a rounded-rectangle with rx==0 or ry==0, do not take it as a drawable element". I wish if the experts give some comments on the direction we should go.

**Comment by mpsuzuki** [comment]
If rx and ry are non-zero, like,
```
<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200" viewBox="0 0 300 200">
  <ellipse cx="150" cy="50" rx="25" ry="25"/>
  <rect x="120" y="120" width="60" height="60" rx="15"  ry="15"/>

  <ellipse cx="50"  cy="50" rx="1" ry="25"/>
  <rect x="20"  y="120" width="60" height="60" rx="1"   ry="15"/>

  <ellipse cx="250" cy="50" rx="50" ry="25"/>
  <rect x="220" y="120" width="60" height="60" rx="150" ry="15"/>
</svg>
```

The result is looking like
![rect2-fixed](https://user-images.githubusercontent.com/2202675/71163083-bb85d780-228f-11ea-8b1d-e597cf003a02.png)

**Comment by mpsuzuki** [comment]
But, if rx == 0, like,
```
<svg xmlns="http://www.w3.org/2000/svg" width="300" height="200" viewBox="0 0 300 200">
  <ellipse cx="150" cy="50" rx="25" ry="25"/>
  <rect x="120" y="120" width="60" height="60" rx="15"  ry="15"/>

  <ellipse cx="50"  cy="50" rx="0" ry="25"/>
  <rect x="20"  y="120" width="60" height="60" rx="0"   ry="15"/>

  <ellipse cx="250" cy="50" rx="50" ry="25"/>
  <rect x="220" y="120" width="60" height="60" rx="150" ry="15"/>
</svg>
```

The source at abfb9aac9e14369a6f1ee67a961331c953111639 gives such result.
![rect2-zero-orig](https://user-images.githubusercontent.com/2202675/71163452-71e9bc80-2290-11ea-9a30-891b37d09fbb.png). You can find the rx == 0 elements (at the left side) are not drawn, and, following elements at the right sides are not drawn at all. It is what I call as "paralyzed".

**Comment by mpsuzuki** [comment]
The source at abfb9aac9e14369a6f1ee67a961331c953111639, including my 2 patches (one for ellipse, another for rounded-rectangle), the result is like this.
![rect2-zero-fixed](https://user-images.githubusercontent.com/2202675/71163691-f8060300-2290-11ea-8ea9-bab3a5581dbb.png)

The web browsers would show such results.

**Comment by dirkschulze** [comment]
According to https://svgwg.org/svg2-draft/shapes.html#EllipseElement a value of 0 for either rx or ry disables the rendering of the element. Same for r on circle or width/height on rect.

So we should skip the element if one of the attributes is 0.
