### ISSUE TITLE
Wrong file permissions in git repository

### ISSUE THREAD

**Issue by lemzwerg** [adobe/svg-native-viewer#9]
Many files in the git repository (for example, `src/CSSColorKeywords.h` or `test/gradient.txt`) have incorrectly set the executable bit.  Please fix that.

**Comment by dirkschulze** [comment]
I hope I got all files. Please reopen if you should find more.

**Comment by lemzwerg** [comment]
File `svgnative/CMakeLists.txt` has still the executable bit – everything else is fine, thanks!

**Comment by dirkschulze** [comment]
@lanther Fixed, Thanks!
